-- MySQL Script generated by MySQL Workbench
-- Fri Jan  5 23:39:13 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gestit
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestit` DEFAULT CHARACTER SET utf8 ;
USE `gestit` ;

-- -----------------------------------------------------
-- Table `gestit`.`commune`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestit`.`commune` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code_postal` INT NULL DEFAULT NULL,
  `nom` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestit`.`adresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestit`.`adresse` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NULL DEFAULT NULL,
  `voie` VARCHAR(255) NULL DEFAULT NULL,
  `commune_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK85m6y7vy6lfud2ae3tnq375of` (`commune_id` ASC) VISIBLE,
  CONSTRAINT `FK85m6y7vy6lfud2ae3tnq375of`
    FOREIGN KEY (`commune_id`)
    REFERENCES `gestit`.`commune` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestit`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestit`.`utilisateur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_non_valide` DATE NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `mot_de_passe` VARCHAR(255) NULL DEFAULT NULL,
  `nom` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestit`.`marque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestit`.`marque` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestit`.`modele`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestit`.`modele` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NULL DEFAULT NULL,
  `marque_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK8y0qsdtgm60haj45cmgypuvf6` (`marque_id` ASC) VISIBLE,
  CONSTRAINT `FK8y0qsdtgm60haj45cmgypuvf6`
    FOREIGN KEY (`marque_id`)
    REFERENCES `gestit`.`marque` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestit`.`vehicule_perso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestit`.`vehicule_perso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `immatriculation` VARCHAR(255) NULL DEFAULT NULL,
  `nombre_de_place_disponibles` INT NULL DEFAULT NULL,
  `statut` ENUM('SUPPRIMER') NULL DEFAULT NULL,
  `modele_id` INT NULL DEFAULT NULL,
  `proprietaire_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK9rrbpgwynygc9e6dxrluw66pj` (`modele_id` ASC) VISIBLE,
  INDEX `FKlra1uavm94k0iy3y87rr5xcfl` (`proprietaire_id` ASC) VISIBLE,
  CONSTRAINT `FK9rrbpgwynygc9e6dxrluw66pj`
    FOREIGN KEY (`modele_id`)
    REFERENCES `gestit`.`modele` (`id`),
  CONSTRAINT `FKlra1uavm94k0iy3y87rr5xcfl`
    FOREIGN KEY (`proprietaire_id`)
    REFERENCES `gestit`.`utilisateur` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestit`.`covoiturage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestit`.`covoiturage` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_depart` DATE NULL DEFAULT NULL,
  `distance_km` INT NULL DEFAULT NULL,
  `duree_trajet` INT NULL DEFAULT NULL,
  `nombre_places_restantes` INT NULL DEFAULT NULL,
  `adresse_arrivee_id` INT NULL DEFAULT NULL,
  `adresse_depart_id` INT NULL DEFAULT NULL,
  `organisateur_id` INT NULL DEFAULT NULL,
  `vehicule_perso_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKbua1pqlugqx4k0c6g4i0k9la1` (`adresse_arrivee_id` ASC) VISIBLE,
  INDEX `FKm2kpb3ef2mjivibmtgltfomc5` (`adresse_depart_id` ASC) VISIBLE,
  INDEX `FK50108k1ra3ns71tup24vu1kxq` (`organisateur_id` ASC) VISIBLE,
  INDEX `FKp7j10vdqhi2gkapw5ruqr105r` (`vehicule_perso_id` ASC) VISIBLE,
  CONSTRAINT `FK50108k1ra3ns71tup24vu1kxq`
    FOREIGN KEY (`organisateur_id`)
    REFERENCES `gestit`.`utilisateur` (`id`),
  CONSTRAINT `FKbua1pqlugqx4k0c6g4i0k9la1`
    FOREIGN KEY (`adresse_arrivee_id`)
    REFERENCES `gestit`.`adresse` (`id`),
  CONSTRAINT `FKm2kpb3ef2mjivibmtgltfomc5`
    FOREIGN KEY (`adresse_depart_id`)
    REFERENCES `gestit`.`adresse` (`id`),
  CONSTRAINT `FKp7j10vdqhi2gkapw5ruqr105r`
    FOREIGN KEY (`vehicule_perso_id`)
    REFERENCES `gestit`.`vehicule_perso` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestit`.`covoiturages_collaborateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestit`.`covoiturages_collaborateur` (
  `covoiturage_id` INT NOT NULL,
  `collaborateur_id` INT NOT NULL,
  INDEX `FK4vvbmhc5yy0or8b45obpqs98i` (`collaborateur_id` ASC) VISIBLE,
  INDEX `FKbs321v8h0uods3hlwqlv9c6nd` (`covoiturage_id` ASC) VISIBLE,
  CONSTRAINT `FK4vvbmhc5yy0or8b45obpqs98i`
    FOREIGN KEY (`collaborateur_id`)
    REFERENCES `gestit`.`utilisateur` (`id`),
  CONSTRAINT `FKbs321v8h0uods3hlwqlv9c6nd`
    FOREIGN KEY (`covoiturage_id`)
    REFERENCES `gestit`.`covoiturage` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestit`.`vehicule_service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestit`.`vehicule_service` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `immatriculation` VARCHAR(255) NULL DEFAULT NULL,
  `nombre_de_place_disponibles` INT NULL DEFAULT NULL,
  `categorie` ENUM('BERLINES_TAILLE_L', 'BERLINES_TAILLE_M', 'BERLINES_TAILLE_S', 'CITADINES_POLYVALENTES', 'COMPACTES', 'MICRO_URBAINES', 'MINI_CITADINES', 'SUV_TOUT_TERRAINS_PICKUP') NULL DEFAULT NULL,
  `emission_co2` DOUBLE NULL DEFAULT NULL,
  `motorisation` ENUM('ELECTRIQUE', 'HYBRIDE', 'THERMIQUE') NULL DEFAULT NULL,
  `photo_url` VARCHAR(255) NULL DEFAULT NULL,
  `statut` ENUM('EN_REPARATION', 'EN_SERVICE', 'HORS_SERVICE') NULL DEFAULT NULL,
  `modele_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKt6ewqodbwm43eo878uuqvrakv` (`modele_id` ASC) VISIBLE,
  CONSTRAINT `FKt6ewqodbwm43eo878uuqvrakv`
    FOREIGN KEY (`modele_id`)
    REFERENCES `gestit`.`modele` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestit`.`reservation_vehicule_service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestit`.`reservation_vehicule_service` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_heure_depart` DATETIME(6) NULL DEFAULT NULL,
  `date_heure_retour` DATETIME(6) NULL DEFAULT NULL,
  `collaborateur_id` INT NULL DEFAULT NULL,
  `vehicule_service_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKj1vjldv9s25741qvsal40w8mv` (`collaborateur_id` ASC) VISIBLE,
  INDEX `FKt5105g4iogxlagxnbjrbnty90` (`vehicule_service_id` ASC) VISIBLE,
  CONSTRAINT `FKj1vjldv9s25741qvsal40w8mv`
    FOREIGN KEY (`collaborateur_id`)
    REFERENCES `gestit`.`utilisateur` (`id`),
  CONSTRAINT `FKt5105g4iogxlagxnbjrbnty90`
    FOREIGN KEY (`vehicule_service_id`)
    REFERENCES `gestit`.`vehicule_service` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestit`.`utilisateur_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestit`.`utilisateur_roles` (
  `utilisateur_id` INT NOT NULL,
  `roles` VARCHAR(255) NULL DEFAULT NULL,
  INDEX `FK9lop304xtodorgho9w56lpjhn` (`utilisateur_id` ASC) VISIBLE,
  CONSTRAINT `FK9lop304xtodorgho9w56lpjhn`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `gestit`.`utilisateur` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
